[package]
name = "blog-comments-rust"
version = "0.1.0"
authors = ["stwissel <stw@linux.com>"]
edition = "2018"
license = "Apache 2.0"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.0"
config = "0.10.1"
serde = "1.0.106"
chrono = "0.4.11"